version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: proyecto
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: clave123
    ports:
      - "5432:5432"
    networks:
      - springnet
    restart: always

  app:
    build: .
    container_name: app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/proyecto
      SPRING_DATASOURCE_USERNAME: usuario
      SPRING_DATASOURCE_PASSWORD: clave123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - springnet
    restart: always

networks:
  springnet:
